### ISSUE TITLE
Working in Emacs 25?

### ISSUE THREAD

**Issue by technician77** [ska2342/highlight-context-line#1]
Would this package work on Emacs 25? Tried everything but it doesn't seem to work on my Emacs [GNU Emacs 25.1.1 (x86_64-w64-mingw32) of 2016-11-15] It's sad, because the idea is quite good.

**Comment by ska2342** [comment]
I have a self-compiled Emacs 25.1.1 and it just works.  Did you enable the mode, e.g. with `M-x highlight-context-line-mode`?

**Comment by ska2342** [comment]
@technician77 any news on this from your side?

**Comment by technician77** [comment]
Well, you can close the case. It works in the official compiled windows version of emacs 25. It seems to be a problem with my config. When removing 99% it works. Tried to find the culprit, but no luck so far. I have a fairly large config and finding the problem source is quite time consuming.

**Comment by ska2342** [comment]
I'll keep this open for a while. Maybe you can isolate the problem.

Did you try to `debug-on-error`?  Is your config public so that I could have a look? Anything else I can do to help?

**Comment by ska2342** [comment]
Hm. Closing now.
